# Generated by Django 2.2.7 on 2019-12-04 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('profil', models.TextField(null=True)),
                ('dateInscription', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'ordering': ['pseudo'],
            },
        ),
    ]
